version: '3.4'

services:
  login.api:
    image: ${DOCKER_REGISTRY-}loginapi
    container_name: loginApi
    restart: always
    build:
      context: .
      dockerfile: Services/Login/Login.API/Dockerfile
    ports:
      - "5000:80"
      - "8080:8080"

  loginDb:
     image: mcr.microsoft.com/mssql/server:2017-latest
     container_name: loginDb
     environment:
        SA_PASSWORD: "Lebio12345678"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
     restart: always
     ports:
        - "1433:1433"